services:
  # Django Backend Service
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: 'gamedb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Caching Service
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

  # --- LOCUST SERVICE ---
  locust:
    build: ./locust_docker 
    container_name: locust
    command: -f /mnt/locust/locustfile.py --host http://backend:8000
    volumes:
      - ./load_tests:/mnt/locust
    ports:
      - "8089:8089" # Web UI
      - "8090:8090" # Exporter port
    depends_on:
      - backend

  # --- MONITORING SERVICES ---
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - locust 

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:11.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mysql_data: