services:
  # Our Django Backend Service
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # Our MySQL Database Service
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: 'gamedb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck: # <-- This is the new section
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Our Redis Caching Service
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: